export const FETCH_DETAILS_BY_ID_INIT = "FETCH_DETAILS_BY_ID_INIT";
export const FETCH_DETAILS_BY_ID_SUCCESS = "FETCH_DETAILS_BY_ID_SUCCESS";
export const FETCH_DETAILS_BY_ID_FAILURE = "FETCH_DETAILS_BY_ID_FAILURE";
