export const FETCH_RANDOM_DETAILS_INIT = "FETCH_RANDOM_DETAILS_INIT";
export const FETCH_RANDOM_DETAILS_SUCCESS = "FETCH_RANDOM_DETAILS_SUCCESS";
export const FETCH_RANDOM_DETAILS_FAILURE = "FETCH_RANDOM_DETAILS_FAILURE";
